### PR TITLE
Pledge Math Function(s)

### PR DESCRIPTION
**Pull request by shannonfromomaha**

### CODE REVIEW

**Comment by shannonfromomaha** [comment]
trying to use a conditional to display a specific message if you get redirected to this page, it redirects but does not show.

**Comment by halfghaninne** [comment]
Have you used `binding.pry` to investigate the value of `@over` ?

**Comment by jillianw** [comment]
Yep -- tried that.

**Comment by halfghaninne** [comment]
Coming over.

**Pull request merged**
